name: 部署文档

on:
  push:
    tags:
      - "doc*"

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: 展示版本
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        id: image-name
        run: |-
          pnpm --filter=vanblog-docs docs:build

      - name: 打包镜像并推送
        uses: docker/build-push-action@v2
        with:
          context: ./docs
          file: ./docs/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            "docker.io/mereith/van-blog-website:${{ steps.get_version.outputs.VERSION }}"

      - name: 部署到集群
        uses: steebchen/kubectl@v2.0.0
        with:
          # defaults to latest kubectl binary version
          config: ${{ secrets.K8S_CONFIG_DATA }}
          command: set image  deployment/vanblog-doc vanblog-doc=docker.io/mereith/van-blog-website:${{ steps.get_version.outputs.VERSION }}

      # - name: send Message To me
      #   run: |
      #     curl -X POST -H "Content-Type: application/json" -d '{"source":"github-ci:van-blog-doc","message":"流水线运行完毕，${{ steps.get_version.outputs.VERSION }} 已部署"}'  ${{ secrets.WEBHOOK_URL }}
